version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./:/root
    depends_on:
      - redis    
    networks:
      - app-network
    command: [
      "./bot",
      "-history=${HISTORY:-/root/result.json}",
      "-prompt=${PROMPT:-/root/prompt.txt}",
      "-model=${MODEL:-claude-3-5-sonnet-20240620}",
      "-provider=${PROVIDER:-anthropic}",
      "-spam-threshold=${SPAM_THRESHOLD:-0.6}",
      "-new-user-threshold=${NEW_USER_THRESHOLD:-1}",
      "-whitelist-channels=${WHITELIST_CHANNELS:-}", # comma separated, for example: "-1001098030726" (CTO daily chat)
      "-log-level=${LOG_LEVEL:-info}"
    ]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel warning
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge